[package]
name = "allocator"
version = "0.1.0"
authors = ["0xErwin1"]
description = ""
keywords = []
license = "MIT"
repository = ""

[ignis]
std = true
std_path = "../../std"
runtime_path = "../../std/runtime"

[build]
bin = true
source_dir = "src"
entry = "main.ign"
out_dir = "build"
opt_level = 2
debug = true
target = "c"
cc = "gcc"
cflags = ["-Wall"]
emit = ["c"]
