[package]
name = "ignis"
version = "0.1.0"
authors = []
description = "A Ignis project"
keywords = []
license = "MIT"
repository = ""

[ignis]
std = true

[aliases]
"@" = "./src"

[build]
bin = true
source_dir = "src"
entry = "main.ign"
out_dir = "build"
opt_level = 0
debug = false
target = "c"
cc = "cc"
cflags = []
emit = []

