# Ignis Standard Library Manifest
#
# This file describes the available modules and their linking requirements.

[modules]
# Module name = relative path to .ign file
io = "io/mod.ign"
math = "math/mod.ign"
string = "string/mod.ign"
number = "number/mod.ign"
types = "types/mod.ign"

[linking.io]
# I/O module uses custom runtime functions
header = "runtime/io/io.h"
object = "runtime/io/libignis_io.o"

[linking.math]
# Math module uses standard C math library
header = "math.h"
# No custom object needed - links against libm

[linking.string]
# String module uses custom runtime functions
header = "runtime/string/string.h"
object = "runtime/string/libignis_string.o"

[linking.number]
# Number module uses custom runtime functions
header = "runtime/number/number.h"
object = "runtime/number/libignis_number.o"

[linking.types]
# Types module uses custom runtime functions
header = "runtime/types/types.h"
object = "runtime/types/libignis_types.o"

# [auto_load]
# modules = ["prelude"]
